services:
  web:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    container_name: django_web
    env_file: .env
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      - mysql
    networks:
      - djangonet

  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: django_bot
    env_file: .env
    depends_on:
      - web
    networks:
      - djangonet

  mysql:
    image: mysql:8.0
    container_name: django_mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - djangonet

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - djangonet

volumes:
  static_data:
  media_data:
  db_data:

networks:
  djangonet:
